### ISSUE TITLE
Setup PR validation workflow using CircleCI

### ISSUE THREAD

**Issue by chirino** [chirino/graphql-gw#12]
Something like https://github.com/skupperproject/skupper-cli/blob/master/.circleci/config.yml
would be handy..  Where it can also do the release builds when tags are created.

**Comment by wtrocki** [comment]
That is already done using github actions (they faster than circleci)

**Comment by machi1990** [comment]
> That is already done using github actions (they are faster than circleci)

@wtrocki any pointers for the GH action?

**Comment by wtrocki** [comment]
Hi

All builds are here:
https://github.com/chirino/graphql-gw/actions

Do you want to create GH actions on different project?

**Comment by machi1990** [comment]
> Hi
> 
> All builds are here:
> https://github.com/chirino/graphql-gw/actions
> 
> Do you want to create GH actions on different project?

The Circle CI workflow shared above seemed rich (like it can do a lot of things), was curious to see if there is already a GH action that does something similar: even though we can argue that it is mostly bash scripts and yaml files  And possibly, see if I could add it in this project (to fix the issue).

**Comment by wtrocki** [comment]
My opinion:

GH action - fast reliable close to source easy to setup and extend. I haven't done any crazy stuff like starting kubernetes for tests.

CircleCI more suited for complex use cases. More docker friendly.

I started configuring GitHub ones as it is simply easier to build and manage. Linked config can be ported to GitHub actions

**Comment by chirino** [comment]
it's working. thx
