### ISSUE TITLE
Ability to override config by env variables

### ISSUE THREAD

**Issue by wtrocki** [chirino/graphql-gw#14]
I build docker container. For container natural option will be to have volume with config however as config grows it might make sense to use environment variables for URLs that can change between Dev prod. Just idea with low priority

**Comment by wtrocki** [comment]
https://github.com/chirino/graphql-gw/pull/16

**Comment by chirino** [comment]
great idea!  Even better if we can also default values:
like url: ${MYURL:http://mytest.com/foo}
