### ISSUE TITLE
Implement the data loader pattern

### ISSUE THREAD

**Issue by chirino** [chirino/graphql-gw#2]
Use the data loader pattern to collect multiple requests that would be performed against the same graphql endpoint and batch them into a single request. 

see:
https://medium.com/@__xuorig__/the-graphql-dataloader-pattern-visualized-3064a00f319f

**Comment by wtrocki** [comment]
Quick question - if schema is federated do we need to actually use batching? Usually this happens on the service level but not on federated api

**Comment by chirino** [comment]
I think we should be able to reuse https://github.com/graph-gophers/dataloader

**Comment by chirino** [comment]
done.
