### ISSUE TITLE
Create 2-3 services as example for federating graphql schema 

### ISSUE THREAD

**Issue by wtrocki** [chirino/graphql-gw#4]
Proposition to test federation with control over the graphql schemas. 
Can use something like SuperGraph or graphql-serve.
It will be much easier to wrap your head around the concepts if schema will be available for modification etc.

**Comment by chirino** [comment]
I just added few really quick ones here: [characters](https://github.com/chirino/graphql-gw/blob/master/internal/gateway/examples/characters/characters.go) and [shows](https://github.com/chirino/graphql-gw/blob/master/internal/gateway/examples/shows/shows.go)

We can grow them a bit as needed.
