### ISSUE TITLE
[Idea] Ability to add middleware to auto imported schema for various needs

### ISSUE THREAD

**Issue by wtrocki** [chirino/graphql-gw#8]
Implementation works perfectly with fetching all details from custom services but it will be nice to be able to define some form of middleware or ability to perform modification on service graphql.

Where this can be useful:

- Adding metrics
- Adding rate limiting etc.
- Adding authentication

**Comment by chirino** [comment]
This seems kinda similar to #33.

**Comment by wtrocki** [comment]
Yes. This is exactly the same requirement. Closing
