### ISSUE TITLE
[Test] Custom scalar support

### ISSUE THREAD

**Issue by wtrocki** [chirino/graphql-gw#9]
This might be challenging but I would like to see how export will work with the scalars in the schema. https://anilist.github.io/ApiV2-GraphQL-Docs/ doesn't seem to be using any scalars.

**Comment by chirino** [comment]
Anilist actually does some scalars.  Use this query to see one in action:

```graphql
query {
  Media(id:527) {
    title {
      english
    }
    format
    countryOfOrigin
  }
}
```

The `countryOfOrigin` of of type `CountryCode`

**Comment by wtrocki** [comment]
My bad. In fact, I can get the proper results. Closing
